// any declaration here bypasses anything generated by the server

// by pass definitions
var developmentflag = false;
// accepts -1 (off) or flag [0,1]
var defaultPresence = 1;
var reportWarning = "";
