// any declaration here bypasses anything generated by the server

// ip = "";
// samplingWindow = 5 * 1000;
// reportCurrent = false;
// user = "";
// spaceTimes = {
// "livlab": ["03:00", "05:00"],
// };
// labellength = 8;
// overviewReport = true;
// overviewReportDefs = [ {name: "at 10:00", start: "", end: "", point: "10:00", precision: "30", presence: "", id: 0},];
// refOverviewAsys = "20secs";
// overviewSkipDays = ["0", "6"];
// rtshow = "";
// repshow = "";
// openingTime = "";
// opStartTime = "";
// opEndTime = "";

var developmentflag = false;
// accepts -1 (off) or flag [0,1]
var defaultPresence = 1;
var reportWarning = "";
