// any declaration here bypasses anything generated by the server

// turn off/on presence chack based on occupancy samples
var noSamplePresenceCheck = false;

// presence default accepts -1 (off) or flag [0,1]
var defaultPresence = 1;

// custom warning on report header
var reportWarning = "";

// measurement aliases, need to be inserted manually once
var aliasMeasurement = {
"20secs": "AVG last 20s", 
"20mins": "AVG last 20m", 
"hour": "AVG last hour", 
"day": "AVG last 24h"
}
